version: "3.9"

services:
  wordpress:
    image: wordpress:6.4
    container_name: fittribe_wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    container_name: fittribe_db
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql

  fastapi:
    build: ./fastapi-backend
    container_name: fittribe_fastapi
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-backend:/app
    depends_on:
      - fastapi_db

  fastapi_db:
    image: postgres:14
    container_name: fittribe_fastapi_db
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fittribe_db
    volumes:
      - fastapi_pgdata:/var/lib/postgresql/data

  go-service:
    build: ./go-gamification
    container_name: fittribe_go
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./go-gamification:/go/src/app
    depends_on:
      - fastapi

volumes:
  db_data:
  fastapi_pgdata:
